services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_pass
      POSTGRES_DB: notes_db
    volumes:
      - pgdata:/var/lib/postgresql/data


  api:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://notes_user:notes_pass@db:5432/notes_db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: